#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


FORBIDDEN_HTTPS_URL1="https://github.com/Runnect/Runnect-Server" # insert your remote url (https)
FORBIDDEN_HTTPS_URL2="https://github.com/Runnect/Runnect-Server.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:Runnect/Runnect-Server.git" # insert your remote url (ssh)
FORBIDDEN_REF_MAIN="refs/heads/main" # insert branch ref
FORBIDDEN_REF_DEV="refs/heads/dev"

remote="$1" #$1 -- push 가 수행될 원격 저장소의 이름  (예: origin)
url="$2" #$2 -- push 가 이루어질 원격 저장소의 URL 정보 (예: https://://.git)



if [ "$url" != "$FORBIDDEN_HTTPS_URL1" -a "$url" != "$FORBIDDEN_HTTPS_URL2" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    echo "포크된 브런치는 커밋을 푸쉬할 수 있습니다."
    exit 0 # Forked Project 에서는 제한하지 않음
fi

if read local_ref local_sha remote_ref remote_sha
then
  # local_ref : refs/heads/main : branch
  # local_sha : commit num
  echo "현재 푸쉬하는 브랜치는 $local_ref 내부입니다."
    if [ "$remote_ref" == "$FORBIDDEN_REF_MAIN" ] || [ "$remote_ref" == "$FORBIDDEN_REF_DEV" ]
    then
        echo "DO NOT PUSH TO MAIN OR DEV"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
fi

exit 0
