#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


FORBIDDEN_HTTPS_URL="https://github.com/Runnect/Runnect_Server.git" # insert your remote url (https)
FORBIDDEN_SSH_URL="git@github.com:Runnect/Runnect_Server.git" # insert your remote url (ssh)
FORBIDDEN_REF_MAIN="refs/heads/main" # insert branch ref
FORBIDDEN_REF_DEV="refs/heads/dev"

remote="$1"
echo "remote : $remote"
url="$2"
echo "url : $url"

echo "밖 local_ref : $local_ref"


if read local_ref local_sha remote_ref remote_sha
then
  echo "안 local_ref : $local_ref"
  echo "안 local_sha : $local_sha"
  echo "안 remote_ref : $remote_ref"
  echo "안 remote_sha : $remote_sha"
  echo "현재 푸쉬하는 브랜치는 $local_ref 내부입니다."
    if [ "$remote_ref" == "$FORBIDDEN_REF_MAIN" ] || [ "$remote_ref" == "$FORBIDDEN_REF_DEV" ]
    then
        echo "DO NOT PUSH TO MAIN OR DEV"
        exit 1 # 금지된 ref 로 push 를 실행하면 에러
    fi
  exit 1
fi

exit 1